application: stockpredictr
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: stockpredictr.py
  login: admin

- url: /.*
  script: stockpredictr.py
