application: stockpredictr
version: 8
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /admin/.*
  script: stockpredictr.py
  login: admin

- url: /.*
  script: stockpredictr.py
